name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - main # プルリク対象のブランチを指定（必要に応じて変更）

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12 # 使用するPythonのバージョンを指定

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run pytest
        run: pytest -v

  add_comment:
    if: failure() # test ジョブが失敗した場合にのみ実行
    needs: test # test ジョブに依存
    runs-on: ubuntu-latest

    steps:
      - name: Add comment to the pull request if tests fail
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          COMMENT="⚠️ テストが失敗しています。エラーを解決してからマージしてください。"
          curl -X POST \
               -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -d "{\"body\": \"$COMMENT\"}" \
               "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
